/**
 * Synced Product Catalog Data
 * Automatically generated by scripts/sync-catalog.mjs from kitchen-bots-ecommerce.
 * DO NOT EDIT MANUALLY. Run 'npm run sync:catalog' to refresh.
 */

import { CommerceProduct, CommerceInventory, CommerceWarehouse } from '../types/commerce';

export interface CategoryContent {
  id: string;
  name: string;
  headline: string;
  intro: string;
  technicalExplanation: string;
  usageScenarios: string[];
  highlight: string;
}

export const SYNCED_CATEGORIES: CategoryContent[] = [
  {
    "id": "collapsible-bbq",
    "name": "Collapsible BBQ",
    "headline": "Flat-Pack Performance. Zero Compromise.",
    "intro": "The KitchenBots Collapsible BBQ range is engineered for people who demand professional-grade grilling without a permanent installation. Each unit folds completely flat in under 60 seconds, fits in the boot of any hatchback, and opens into a full-sized, high-heat cooking station.",
    "technicalExplanation": "Constructed from precision-laser-cut mild steel with heat-resistant ceramic coating, our collapsible grills use an interlocking panel system that creates a rigid structural frame when open — without a single bolt. Internal airflow channels direct oxygen from the base through the charcoal bed to the cooking surface, achieving cooking temperatures of 250°C–400°C.",
    "usageScenarios": [
      "Backyard weekend BBQs and family gatherings",
      "Rooftop and terrace cooking events",
      "Camping, trekking, and beach cookouts",
      "Catering events and outdoor food stalls",
      "Commercial kitchen overflow capacity"
    ],
    "highlight": "Folds to 90mm flat. Sets up in under 60 seconds."
  },
  {
    "id": "rocket-stoves",
    "name": "Rocket Stoves",
    "headline": "Maximum Heat. Minimum Fuel. Zero Smoke.",
    "intro": "Rocket stoves are the most thermally efficient cooking technology ever designed for solid-fuel combustion. The KitchenBots Rocket Stove takes this concept to its engineering limit — delivering intense, consistent, low-smoke heat from a fraction of the wood or charcoal used by traditional open fires.",
    "technicalExplanation": "Our rocket stoves use an L-shaped combustion chamber with a precision-engineered cross-section ratio. Preheated combustion air enters from the fuel feed, surrounds the burning material, and is directed vertically through the insulated riser. The result: secondary combustion of gases that would otherwise escape as smoke — a 60–75% improvement in thermal efficiency over open-fire cooking.",
    "usageScenarios": [
      "Off-grid outdoor cooking and jungle camping",
      "Commercial tandoor and wok cooking stations",
      "Agricultural and rural kitchen setups",
      "Disaster relief and emergency field kitchens",
      "Eco-conscious home outdoor cooking"
    ],
    "highlight": "Up to 75% less fuel than open fires. Rated to 1100°C."
  },
  {
    "id": "automatic-bbq",
    "name": "Automatic BBQ",
    "headline": "Set It. Forget It. Serve Perfect Every Time.",
    "intro": "The KitchenBots Automatic BBQ series introduces motorised rotation technology to Indian outdoor cooking. Dual-speed AC/DC motors keep multiple skewers at optimal distance from the charcoal bed — delivering uniform browning without manual attention.",
    "technicalExplanation": "The motorised spit system operates on a 240V AC mains power with an optional 12V DC battery adapter for off-grid events. The rotation speed is engineered to create a continuous Maillard reaction across the entire surface of the food — eliminating hot spots and cold zones. Built entirely from 304-grade food-safe stainless steel with no painted internal surfaces.",
    "usageScenarios": [
      "Commercial restaurant rotisserie and shawarma counters",
      "Event catering and banquet services",
      "High-volume public cooking events",
      "Professional outdoor kitchens",
      "Wedding and hospitality catering"
    ],
    "highlight": "Feeds 20–30 people simultaneously. Food-grade SS throughout."
  },
  {
    "id": "santa-maria",
    "name": "Santa Maria Series",
    "headline": "Argentinian Fire Mastery. Indian Engineering.",
    "intro": "The Santa Maria Series is KitchenBots' flagship live-fire cooking system — inspired by the traditional Argentinian asado grill. A precision crank-wheel elevation mechanism lets the cook control cooking temperature by adjusting grate height above the fire, achieving results impossible with any other grill design.",
    "technicalExplanation": "The elevation system uses a ratchet-lock wheel with 24 discrete positions across a 400mm height range. V-groove grates capture and redirect meat drip as flavour smoke rather than causing flare-ups. The main structure is constructed from heavy-gauge 3mm mild steel plate, stress-relieved by heat treatment after fabrication for maximum dimensional stability.",
    "usageScenarios": [
      "Centrepiece outdoor kitchen installation",
      "Live-fire cooking demonstrations and restaurants",
      "Large family gatherings and social events",
      "Luxury catering and event hire",
      "Serious home cook installations"
    ],
    "highlight": "Crank-wheel elevation. V-groove grates. 400mm height range."
  },
  {
    "id": "suitcase-bbq",
    "name": "Suitcase BBQ",
    "headline": "The World's Most Portable Serious Grill.",
    "intro": "The Suitcase BBQ is engineered for people who refuse to compromise on quality when cooking away from home. It folds to a slim 70–90mm profile with carry handles, and opens into a fully rigid BBQ station in under 30 seconds — no tools required.",
    "technicalExplanation": "A proprietary dual-hinge folding system allows the entire unit — including the charcoal tray, cooking grate, and windshield panels — to collapse into a single flat case. The internal locking mechanism generates a structural rigidity equivalent to a fixed-base unit, distributing load evenly across the welded frame.",
    "usageScenarios": [
      "Adventure travel and road trips",
      "Beach and riverside cookouts",
      "Balcony and apartment terrace cooking",
      "Picnics, parks, and campsite grilling",
      "Gift for the serious outdoor cook"
    ],
    "highlight": "Folds to 70mm. Sets up in 30 seconds. No tools required."
  },
  {
    "id": "accessories",
    "name": "Accessories",
    "headline": "The Right Tools for the Perfect Cook.",
    "intro": "Every KitchenBots accessory is designed specifically to complement our grill systems. From heavy-duty grate brushes to stainless skewer sets and insulated carry covers — our accessories are built to the same standard as the grills themselves.",
    "technicalExplanation": "KitchenBots accessories are manufactured from food-safe 304 stainless steel or premium heat-treated mild steel. All products are tested for compatibility with our full grill range. Where applicable, accessories carry the same heat-resistance certification as the main units.",
    "usageScenarios": [
      "Extending the functionality of an existing KitchenBots grill",
      "Professional catering toolkit",
      "Gifting and retail bundling",
      "Replacement parts for extended product life"
    ],
    "highlight": "Engineered for KitchenBots. Compatible across the range."
  }
];

export const SYNCED_PRODUCTS: CommerceProduct[] = [
  {
    "id": "prod-1",
    "sku": "KB-SM-001",
    "name": "Commercial BBQ Grill",
    "category": "Santa Maria Series",
    "brand": "KitchenBots",
    "shortDescription": "Stainless steel commercial charcoal/gas BBQ grill built for heavy use.",
    "description": "Stainless steel commercial charcoal/gas BBQ grill built for heavy use.",
    "status": "Active",
    "visibility": "Public",
    "isFeatured": true,
    "tags": [
      "santa-maria-series",
      "stainless-steel",
      "heavy-duty",
      "even-heat",
      "kitchenbots"
    ],
    "images": [
      {
        "id": "img-prod-1-1",
        "url": "/images/products/kb-commercial-bbq.webp",
        "type": "image",
        "isPrimary": true,
        "order": 0
      }
    ],
    "specifications": [
      {
        "id": "spec-prod-1-1",
        "group": "General",
        "name": "Material",
        "value": "Stainless Steel"
      }
    ],
    "variants": [
      {
        "id": "VAR-001-NG",
        "productId": "prod-1",
        "sku": "KB-SM-001-NG",
        "name": "Commercial BBQ - Natural Gas",
        "price": 18000,
        "status": "Active",
        "images": [],
        "specifications": [],
        "weightUnit": "kg",
        "attributes": {
          "fuelType": "Natural Gas"
        }
      },
      {
        "id": "VAR-001-LP",
        "productId": "prod-1",
        "sku": "KB-SM-001-LP",
        "name": "Commercial BBQ - LPG / Charcoal",
        "price": 18000,
        "status": "Active",
        "images": [],
        "specifications": [],
        "weightUnit": "kg",
        "attributes": {
          "fuelType": "LPG"
        }
      }
    ],
    "createdAt": "2026-09-23T00:00:00.000Z",
    "updatedAt": "2026-09-23T00:00:00.000Z"
  },
  {
    "id": "prod-2",
    "sku": "KB-RS-002",
    "name": "Rocket Stove (Single Burner)",
    "category": "Rocket Stoves",
    "brand": "KitchenBots",
    "shortDescription": "Highly efficient single burner rocket stove for outdoor/commercial cooking.",
    "description": "Highly efficient single burner rocket stove for outdoor/commercial cooking.",
    "status": "Active",
    "visibility": "Public",
    "isFeatured": true,
    "tags": [
      "rocket-stoves",
      "high-heat-output",
      "fuel-efficient",
      "portable",
      "kitchenbots"
    ],
    "images": [
      {
        "id": "img-prod-2-1",
        "url": "/images/products/kb-rocket-stove.webp",
        "type": "image",
        "isPrimary": true,
        "order": 0
      },
      {
        "id": "img-prod-2-2",
        "url": "/images/products/6_Visualise Files - Rocket Stove_150MM/Rocket Stove (Single Burner)- Paint Model 1.jpg",
        "type": "image",
        "isPrimary": false,
        "order": 1
      },
      {
        "id": "img-prod-2-3",
        "url": "/images/products/6_Visualise Files - Rocket Stove_150MM/Rocket Stove (Single Burner)- Paint Model 2.jpg",
        "type": "image",
        "isPrimary": false,
        "order": 2
      },
      {
        "id": "img-prod-2-4",
        "url": "/images/products/6_Visualise Files - Rocket Stove_150MM/Rocket Stove (Single Burner)- Paint Model 3.jpg",
        "type": "image",
        "isPrimary": false,
        "order": 3
      }
    ],
    "specifications": [
      {
        "id": "spec-prod-2-1",
        "group": "General",
        "name": "Material",
        "value": "Steel"
      },
      {
        "id": "spec-prod-2-2",
        "group": "General",
        "name": "Burners",
        "value": "Single"
      }
    ],
    "variants": [
      {
        "id": "var-prod-2-std",
        "productId": "prod-2",
        "sku": "KB-RS-002-STD",
        "name": "Rocket Stove (Single Burner) - Standard",
        "price": 8500,
        "status": "Active",
        "images": [],
        "specifications": [],
        "weightUnit": "kg",
        "attributes": {}
      }
    ],
    "createdAt": "2026-09-23T00:00:00.000Z",
    "updatedAt": "2026-09-23T00:00:00.000Z"
  },
  {
    "id": "prod-3",
    "sku": "KB-ACC-003",
    "name": "Food Processing Machine",
    "category": "Accessories",
    "brand": "KitchenBots",
    "shortDescription": "Industrial food mixer and processor for high-capacity hotel kitchens.",
    "description": "Industrial food mixer and processor for high-capacity hotel kitchens.",
    "status": "Active",
    "visibility": "Public",
    "isFeatured": true,
    "tags": [
      "accessories",
      "high-capacity",
      "stainless-steel-bowl",
      "variable-speed",
      "kitchenbots"
    ],
    "images": [
      {
        "id": "img-prod-3-1",
        "url": "https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&q=80&w=600",
        "type": "image",
        "isPrimary": true,
        "order": 0
      }
    ],
    "specifications": [
      {
        "id": "spec-prod-3-1",
        "group": "General",
        "name": "Material",
        "value": "Stainless Steel"
      },
      {
        "id": "spec-prod-3-2",
        "group": "General",
        "name": "Motor",
        "value": "Commercial Grade"
      }
    ],
    "variants": [
      {
        "id": "var-prod-3-std",
        "productId": "prod-3",
        "sku": "KB-ACC-003-STD",
        "name": "Food Processing Machine - Standard",
        "price": 45000,
        "status": "Active",
        "images": [],
        "specifications": [],
        "weightUnit": "kg",
        "attributes": {}
      }
    ],
    "createdAt": "2026-09-23T00:00:00.000Z",
    "updatedAt": "2026-09-23T00:00:00.000Z"
  },
  {
    "id": "prod-4",
    "sku": "KB-ACC-004",
    "name": "Street Food Griddle",
    "category": "Accessories",
    "brand": "KitchenBots",
    "shortDescription": "Commercial flat griddle/tawa for rapid street food preparation.",
    "description": "Commercial flat griddle/tawa for rapid street food preparation.",
    "status": "Active",
    "visibility": "Public",
    "isFeatured": true,
    "tags": [
      "accessories",
      "thick-hot-plate",
      "even-heating",
      "easy-to-clean",
      "kitchenbots"
    ],
    "images": [
      {
        "id": "img-prod-4-1",
        "url": "/images/products/kb-street-food-griddle.webp",
        "type": "image",
        "isPrimary": true,
        "order": 0
      }
    ],
    "specifications": [
      {
        "id": "spec-prod-4-1",
        "group": "General",
        "name": "Material",
        "value": "Mild Steel/Stainless"
      },
      {
        "id": "spec-prod-4-2",
        "group": "General",
        "name": "Type",
        "value": "Flat Tawa"
      }
    ],
    "variants": [
      {
        "id": "var-prod-4-std",
        "productId": "prod-4",
        "sku": "KB-ACC-004-STD",
        "name": "Street Food Griddle - Standard",
        "price": 12000,
        "status": "Active",
        "images": [],
        "specifications": [],
        "weightUnit": "kg",
        "attributes": {}
      }
    ],
    "createdAt": "2026-09-23T00:00:00.000Z",
    "updatedAt": "2026-09-23T00:00:00.000Z"
  },
  {
    "id": "prod-5",
    "sku": "KB-CBBQ-005",
    "name": "Flip BBQ Height Adjustable",
    "category": "Collapsible BBQ",
    "brand": "KitchenBots",
    "shortDescription": "Premium Flip BBQ with fully adjustable height base.",
    "description": "Premium Flip BBQ with fully adjustable height base.",
    "status": "Active",
    "visibility": "Public",
    "isFeatured": false,
    "tags": [
      "collapsible-bbq",
      "height-adjustable-base",
      "flip-grill-design",
      "premium-build",
      "kitchenbots"
    ],
    "images": [
      {
        "id": "img-prod-5-1",
        "url": "/images/products/kb-flip-bbq-adj.webp",
        "type": "image",
        "isPrimary": true,
        "order": 0
      },
      {
        "id": "img-prod-5-2",
        "url": "/images/products/2_Visualise Files - Flip Base Height Adjustable/Flip High Adjustable Base- Paint Model 1.jpg",
        "type": "image",
        "isPrimary": false,
        "order": 1
      },
      {
        "id": "img-prod-5-3",
        "url": "/images/products/2_Visualise Files - Flip Base Height Adjustable/Flip High Adjustable Base- Paint Model 2.jpg",
        "type": "image",
        "isPrimary": false,
        "order": 2
      }
    ],
    "specifications": [
      {
        "id": "spec-prod-5-1",
        "group": "General",
        "name": "Material",
        "value": "Stainless Steel"
      },
      {
        "id": "spec-prod-5-2",
        "group": "General",
        "name": "Height",
        "value": "Adjustable"
      }
    ],
    "variants": [
      {
        "id": "var-prod-5-std",
        "productId": "prod-5",
        "sku": "KB-CBBQ-005-STD",
        "name": "Flip BBQ Height Adjustable - Standard",
        "price": 15000,
        "status": "Active",
        "images": [],
        "specifications": [],
        "weightUnit": "kg",
        "attributes": {}
      }
    ],
    "createdAt": "2026-09-23T00:00:00.000Z",
    "updatedAt": "2026-09-23T00:00:00.000Z"
  },
  {
    "id": "prod-6",
    "sku": "KB-CBBQ-006",
    "name": "Collapsible BBQ Large",
    "category": "Collapsible BBQ",
    "brand": "KitchenBots",
    "shortDescription": "Large heavy-duty collapsible BBQ for commercial spaces.",
    "description": "Large heavy-duty collapsible BBQ for commercial spaces.",
    "status": "Active",
    "visibility": "Public",
    "isFeatured": false,
    "tags": [
      "collapsible-bbq",
      "high-capacity",
      "foldable-legs",
      "heavy-duty",
      "kitchenbots"
    ],
    "images": [
      {
        "id": "img-prod-6-1",
        "url": "/images/products/kb-collapsible-bbq-big.webp",
        "type": "image",
        "isPrimary": true,
        "order": 0
      },
      {
        "id": "img-prod-6-2",
        "url": "/images/products/3_Visualise Files - Collapsible_BBQ/Collapsible_BBQ- Paint Model 1.jpg",
        "type": "image",
        "isPrimary": false,
        "order": 1
      },
      {
        "id": "img-prod-6-3",
        "url": "/images/products/3_Visualise Files - Collapsible_BBQ/Collapsible_BBQ- Paint Model 2.jpg",
        "type": "image",
        "isPrimary": false,
        "order": 2
      }
    ],
    "specifications": [
      {
        "id": "spec-prod-6-1",
        "group": "General",
        "name": "Material",
        "value": "Stainless Steel"
      },
      {
        "id": "spec-prod-6-2",
        "group": "General",
        "name": "Type",
        "value": "Collapsible"
      }
    ],
    "variants": [
      {
        "id": "var-prod-6-std",
        "productId": "prod-6",
        "sku": "KB-CBBQ-006-STD",
        "name": "Collapsible BBQ Large - Standard",
        "price": 12000,
        "status": "Active",
        "images": [],
        "specifications": [],
        "weightUnit": "kg",
        "attributes": {}
      }
    ],
    "createdAt": "2026-09-23T00:00:00.000Z",
    "updatedAt": "2026-09-23T00:00:00.000Z"
  },
  {
    "id": "prod-7",
    "sku": "KB-CBBQ-007",
    "name": "Collapsible Flip Combo",
    "category": "Collapsible BBQ",
    "brand": "KitchenBots",
    "shortDescription": "Ultimate combination of the collapsible frame and flip grill.",
    "description": "Ultimate combination of the collapsible frame and flip grill.",
    "status": "Active",
    "visibility": "Public",
    "isFeatured": false,
    "tags": [
      "collapsible-bbq",
      "combo-unit",
      "ultimate-flexibility",
      "easy-setup",
      "kitchenbots"
    ],
    "images": [
      {
        "id": "img-prod-7-1",
        "url": "/images/products/kb-collapsible-flip.webp",
        "type": "image",
        "isPrimary": true,
        "order": 0
      },
      {
        "id": "img-prod-7-2",
        "url": "/images/products/4_Visualise Files  - Collapsible_Flip/Collapsible -Flip Combo- Paint Model 1.jpg",
        "type": "image",
        "isPrimary": false,
        "order": 1
      },
      {
        "id": "img-prod-7-3",
        "url": "/images/products/4_Visualise Files  - Collapsible_Flip/Collapsible -Flip Combo- Paint Model 2.jpg",
        "type": "image",
        "isPrimary": false,
        "order": 2
      }
    ],
    "specifications": [
      {
        "id": "spec-prod-7-1",
        "group": "General",
        "name": "Material",
        "value": "Stainless Steel"
      },
      {
        "id": "spec-prod-7-2",
        "group": "General",
        "name": "Combo",
        "value": "Yes"
      }
    ],
    "variants": [
      {
        "id": "var-prod-7-std",
        "productId": "prod-7",
        "sku": "KB-CBBQ-007-STD",
        "name": "Collapsible Flip Combo - Standard",
        "price": 24500,
        "status": "Active",
        "images": [],
        "specifications": [],
        "weightUnit": "kg",
        "attributes": {}
      }
    ],
    "createdAt": "2026-09-23T00:00:00.000Z",
    "updatedAt": "2026-09-23T00:00:00.000Z"
  },
  {
    "id": "prod-8",
    "sku": "KB-CBBQ-008",
    "name": "Collapsible BBQ Small",
    "category": "Collapsible BBQ",
    "brand": "KitchenBots",
    "shortDescription": "Small footprint collapsible BBQ perfect for outdoor spaces.",
    "description": "Small footprint collapsible BBQ perfect for outdoor spaces.",
    "status": "Active",
    "visibility": "Public",
    "isFeatured": false,
    "tags": [
      "collapsible-bbq",
      "small-footprint",
      "collapsible",
      "quick-heating",
      "kitchenbots"
    ],
    "images": [
      {
        "id": "img-prod-8-1",
        "url": "/images/products/kb-collapsible-bbq-small.webp",
        "type": "image",
        "isPrimary": true,
        "order": 0
      },
      {
        "id": "img-prod-8-2",
        "url": "/images/products/5_Visualise Files  - Collapsible_BBQ Small/Collapsible_BBQ Small- Paint Model 1.jpg",
        "type": "image",
        "isPrimary": false,
        "order": 1
      },
      {
        "id": "img-prod-8-3",
        "url": "/images/products/5_Visualise Files  - Collapsible_BBQ Small/Collapsible_BBQ Small- Paint Model 2.jpg",
        "type": "image",
        "isPrimary": false,
        "order": 2
      }
    ],
    "specifications": [
      {
        "id": "spec-prod-8-1",
        "group": "General",
        "name": "Material",
        "value": "Painted Steel"
      },
      {
        "id": "spec-prod-8-2",
        "group": "General",
        "name": "Type",
        "value": "Collapsible Small"
      }
    ],
    "variants": [
      {
        "id": "var-prod-8-std",
        "productId": "prod-8",
        "sku": "KB-CBBQ-008-STD",
        "name": "Collapsible BBQ Small - Standard",
        "price": 6200,
        "status": "Active",
        "images": [],
        "specifications": [],
        "weightUnit": "kg",
        "attributes": {}
      }
    ],
    "createdAt": "2026-09-23T00:00:00.000Z",
    "updatedAt": "2026-09-23T00:00:00.000Z"
  },
  {
    "id": "prod-9",
    "sku": "KB-RS-009",
    "name": "Rocket Stove 150MM",
    "category": "Rocket Stoves",
    "brand": "KitchenBots",
    "shortDescription": "High efficiency 150mm rocket stove.",
    "description": "High efficiency 150mm rocket stove.",
    "status": "Active",
    "visibility": "Public",
    "isFeatured": false,
    "tags": [
      "rocket-stoves",
      "efficiency-burner",
      "150mm-output",
      "heat-focused",
      "kitchenbots"
    ],
    "images": [
      {
        "id": "img-prod-9-1",
        "url": "/images/products/kb-rocket-stove-150.webp",
        "type": "image",
        "isPrimary": true,
        "order": 0
      },
      {
        "id": "img-prod-9-2",
        "url": "/images/products/6_Visualise Files - Rocket Stove_150MM/Rocket Stove (Single Burner)- Paint Model 1.jpg",
        "type": "image",
        "isPrimary": false,
        "order": 1
      },
      {
        "id": "img-prod-9-3",
        "url": "/images/products/6_Visualise Files - Rocket Stove_150MM/Rocket Stove (Single Burner)- Paint Model 2.jpg",
        "type": "image",
        "isPrimary": false,
        "order": 2
      }
    ],
    "specifications": [
      {
        "id": "spec-prod-9-1",
        "group": "General",
        "name": "Material",
        "value": "Painted Steel"
      },
      {
        "id": "spec-prod-9-2",
        "group": "General",
        "name": "Size",
        "value": "150MM"
      }
    ],
    "variants": [
      {
        "id": "var-prod-9-std",
        "productId": "prod-9",
        "sku": "KB-RS-009-STD",
        "name": "Rocket Stove 150MM - Standard",
        "price": 3499,
        "status": "Active",
        "images": [],
        "specifications": [],
        "weightUnit": "kg",
        "attributes": {}
      }
    ],
    "createdAt": "2026-09-23T00:00:00.000Z",
    "updatedAt": "2026-09-23T00:00:00.000Z"
  },
  {
    "id": "prod-10",
    "sku": "KB-RS-010",
    "name": "Rocket Stove Collapsible",
    "category": "Rocket Stoves",
    "brand": "KitchenBots",
    "shortDescription": "Easily transportable collapsible rocket stove.",
    "description": "Easily transportable collapsible rocket stove.",
    "status": "Active",
    "visibility": "Public",
    "isFeatured": false,
    "tags": [
      "rocket-stoves",
      "collapsible-design",
      "fuel-efficient",
      "backpacking-ready",
      "kitchenbots"
    ],
    "images": [
      {
        "id": "img-prod-10-1",
        "url": "/images/products/kb-rocket-stove-coll.webp",
        "type": "image",
        "isPrimary": true,
        "order": 0
      },
      {
        "id": "img-prod-10-2",
        "url": "/images/products/7_Visualise Files - Rocket Stove_Collapsible/Rocket Stove - Collapsible- Paint Model 1.jpg",
        "type": "image",
        "isPrimary": false,
        "order": 1
      },
      {
        "id": "img-prod-10-3",
        "url": "/images/products/7_Visualise Files - Rocket Stove_Collapsible/Rocket Stove - Collapsible- Paint Model 2.jpg",
        "type": "image",
        "isPrimary": false,
        "order": 2
      }
    ],
    "specifications": [
      {
        "id": "spec-prod-10-1",
        "group": "General",
        "name": "Material",
        "value": "Painted Steel"
      },
      {
        "id": "spec-prod-10-2",
        "group": "General",
        "name": "Type",
        "value": "Collapsible"
      }
    ],
    "variants": [
      {
        "id": "var-prod-10-std",
        "productId": "prod-10",
        "sku": "KB-RS-010-STD",
        "name": "Rocket Stove Collapsible - Standard",
        "price": 4200,
        "status": "Active",
        "images": [],
        "specifications": [],
        "weightUnit": "kg",
        "attributes": {}
      }
    ],
    "createdAt": "2026-09-23T00:00:00.000Z",
    "updatedAt": "2026-09-23T00:00:00.000Z"
  },
  {
    "id": "prod-11",
    "sku": "KB-ABBQ-011",
    "name": "Automatic BBQ",
    "category": "Automatic BBQ",
    "brand": "KitchenBots",
    "shortDescription": "Industrial grade automatic rotisserie BBQ.",
    "description": "Industrial grade automatic rotisserie BBQ.",
    "status": "Active",
    "visibility": "Public",
    "isFeatured": false,
    "tags": [
      "automatic-bbq",
      "automated-grilling",
      "even-heat-distribution",
      "rotisserie-setup",
      "kitchenbots"
    ],
    "images": [
      {
        "id": "img-prod-11-1",
        "url": "/images/products/kb-auto-bbq-ss.webp",
        "type": "image",
        "isPrimary": true,
        "order": 0
      },
      {
        "id": "img-prod-11-2",
        "url": "/images/products/8_Visualise Renders  - Automatic BBQ/Automatic BBQ SS Model 2.png",
        "type": "image",
        "isPrimary": false,
        "order": 1
      },
      {
        "id": "img-prod-11-3",
        "url": "/images/products/8_Visualise Renders  - Automatic BBQ/Automatic BBQ SS Model 3.png",
        "type": "image",
        "isPrimary": false,
        "order": 2
      },
      {
        "id": "img-prod-11-4",
        "url": "/images/products/8_Visualise Renders  - Automatic BBQ/Automatic BBQ SS Model 4.png",
        "type": "image",
        "isPrimary": false,
        "order": 3
      }
    ],
    "specifications": [
      {
        "id": "spec-prod-11-1",
        "group": "General",
        "name": "Material",
        "value": "Stainless/Painted"
      },
      {
        "id": "spec-prod-11-2",
        "group": "General",
        "name": "Automation",
        "value": "Yes"
      }
    ],
    "variants": [
      {
        "id": "var-prod-11-std",
        "productId": "prod-11",
        "sku": "KB-ABBQ-011-STD",
        "name": "Automatic BBQ - Standard",
        "price": 12999,
        "status": "Active",
        "images": [],
        "specifications": [],
        "weightUnit": "kg",
        "attributes": {}
      }
    ],
    "createdAt": "2026-09-23T00:00:00.000Z",
    "updatedAt": "2026-09-23T00:00:00.000Z"
  },
  {
    "id": "prod-12",
    "sku": "KB-SM-012",
    "name": "Santa Maria Grill Medium",
    "category": "Santa Maria Series",
    "brand": "KitchenBots",
    "shortDescription": "Medium sized professional Santa Maria Grill with adjustable grate.",
    "description": "Medium sized professional Santa Maria Grill with adjustable grate.",
    "status": "Active",
    "visibility": "Public",
    "isFeatured": false,
    "tags": [
      "santa-maria-series",
      "adjustable-grate-height",
      "wood-fire-pan",
      "medium-pro-size",
      "kitchenbots"
    ],
    "images": [
      {
        "id": "img-prod-12-1",
        "url": "/images/products/kb-santa-maria-med.webp",
        "type": "image",
        "isPrimary": true,
        "order": 0
      },
      {
        "id": "img-prod-12-2",
        "url": "/images/products/9_Visualise Files -Santa Maria Grill Medium/SantaMaria BBQ Meduim- Paint Model 1.jpg",
        "type": "image",
        "isPrimary": false,
        "order": 1
      },
      {
        "id": "img-prod-12-3",
        "url": "/images/products/9_Visualise Files -Santa Maria Grill Medium/SantaMaria BBQ Meduim- Paint Model 2.jpg",
        "type": "image",
        "isPrimary": false,
        "order": 2
      }
    ],
    "specifications": [
      {
        "id": "spec-prod-12-1",
        "group": "General",
        "name": "Material",
        "value": "Stainless/Painted"
      },
      {
        "id": "spec-prod-12-2",
        "group": "General",
        "name": "Size",
        "value": "Medium"
      }
    ],
    "variants": [
      {
        "id": "var-prod-12-std",
        "productId": "prod-12",
        "sku": "KB-SM-012-STD",
        "name": "Santa Maria Grill Medium - Standard",
        "price": 55000,
        "status": "Active",
        "images": [],
        "specifications": [],
        "weightUnit": "kg",
        "attributes": {}
      }
    ],
    "createdAt": "2026-09-23T00:00:00.000Z",
    "updatedAt": "2026-09-23T00:00:00.000Z"
  }
];

export const INITIAL_WAREHOUSES: CommerceWarehouse[] = [
  { id: 'WH-001', name: 'Main Distribution Center', code: 'MDC', location: 'Mumbai', isActive: true },
  { id: 'WH-002', name: 'North Regional Hub', code: 'NRH', location: 'Delhi', isActive: true },
];

export const INITIAL_INVENTORY: CommerceInventory[] = [
  {
    "id": "INV-001",
    "variantId": "VAR-001-NG",
    "warehouseId": "WH-001",
    "currentStock": 45,
    "reservedStock": 5,
    "availableStock": 40,
    "minimumStock": 10,
    "maximumStock": 100,
    "reorderLevel": 15,
    "status": "In_Stock",
    "lastCountAt": "2026-09-23T00:00:00.000Z"
  },
  {
    "id": "INV-002",
    "variantId": "VAR-001-LP",
    "warehouseId": "WH-001",
    "currentStock": 25,
    "reservedStock": 2,
    "availableStock": 23,
    "minimumStock": 5,
    "maximumStock": 50,
    "reorderLevel": 10,
    "status": "In_Stock",
    "lastCountAt": "2026-09-23T00:00:00.000Z"
  },
  {
    "id": "INV-MDC-prod-2",
    "variantId": "var-prod-2-std",
    "warehouseId": "WH-001",
    "currentStock": 17,
    "reservedStock": 1,
    "availableStock": 16,
    "minimumStock": 5,
    "maximumStock": 50,
    "reorderLevel": 8,
    "status": "In_Stock",
    "lastCountAt": "2026-09-23T00:00:00.000Z"
  },
  {
    "id": "INV-NRH-prod-2",
    "variantId": "var-prod-2-std",
    "warehouseId": "WH-002",
    "currentStock": 8,
    "reservedStock": 0,
    "availableStock": 8,
    "minimumStock": 3,
    "maximumStock": 30,
    "reorderLevel": 5,
    "status": "In_Stock",
    "lastCountAt": "2026-09-23T00:00:00.000Z"
  },
  {
    "id": "INV-MDC-prod-3",
    "variantId": "var-prod-3-std",
    "warehouseId": "WH-001",
    "currentStock": 24,
    "reservedStock": 1,
    "availableStock": 23,
    "minimumStock": 5,
    "maximumStock": 50,
    "reorderLevel": 8,
    "status": "In_Stock",
    "lastCountAt": "2026-09-23T00:00:00.000Z"
  },
  {
    "id": "INV-NRH-prod-3",
    "variantId": "var-prod-3-std",
    "warehouseId": "WH-002",
    "currentStock": 11,
    "reservedStock": 0,
    "availableStock": 11,
    "minimumStock": 3,
    "maximumStock": 30,
    "reorderLevel": 5,
    "status": "In_Stock",
    "lastCountAt": "2026-09-23T00:00:00.000Z"
  },
  {
    "id": "INV-MDC-prod-4",
    "variantId": "var-prod-4-std",
    "warehouseId": "WH-001",
    "currentStock": 31,
    "reservedStock": 1,
    "availableStock": 30,
    "minimumStock": 5,
    "maximumStock": 50,
    "reorderLevel": 8,
    "status": "In_Stock",
    "lastCountAt": "2026-09-23T00:00:00.000Z"
  },
  {
    "id": "INV-NRH-prod-4",
    "variantId": "var-prod-4-std",
    "warehouseId": "WH-002",
    "currentStock": 14,
    "reservedStock": 0,
    "availableStock": 14,
    "minimumStock": 3,
    "maximumStock": 30,
    "reorderLevel": 5,
    "status": "In_Stock",
    "lastCountAt": "2026-09-23T00:00:00.000Z"
  },
  {
    "id": "INV-MDC-prod-5",
    "variantId": "var-prod-5-std",
    "warehouseId": "WH-001",
    "currentStock": 38,
    "reservedStock": 1,
    "availableStock": 37,
    "minimumStock": 5,
    "maximumStock": 50,
    "reorderLevel": 8,
    "status": "In_Stock",
    "lastCountAt": "2026-09-23T00:00:00.000Z"
  },
  {
    "id": "INV-NRH-prod-5",
    "variantId": "var-prod-5-std",
    "warehouseId": "WH-002",
    "currentStock": 17,
    "reservedStock": 0,
    "availableStock": 17,
    "minimumStock": 3,
    "maximumStock": 30,
    "reorderLevel": 5,
    "status": "In_Stock",
    "lastCountAt": "2026-09-23T00:00:00.000Z"
  },
  {
    "id": "INV-MDC-prod-6",
    "variantId": "var-prod-6-std",
    "warehouseId": "WH-001",
    "currentStock": 15,
    "reservedStock": 1,
    "availableStock": 14,
    "minimumStock": 5,
    "maximumStock": 50,
    "reorderLevel": 8,
    "status": "In_Stock",
    "lastCountAt": "2026-09-23T00:00:00.000Z"
  },
  {
    "id": "INV-NRH-prod-6",
    "variantId": "var-prod-6-std",
    "warehouseId": "WH-002",
    "currentStock": 20,
    "reservedStock": 0,
    "availableStock": 20,
    "minimumStock": 3,
    "maximumStock": 30,
    "reorderLevel": 5,
    "status": "In_Stock",
    "lastCountAt": "2026-09-23T00:00:00.000Z"
  },
  {
    "id": "INV-MDC-prod-7",
    "variantId": "var-prod-7-std",
    "warehouseId": "WH-001",
    "currentStock": 22,
    "reservedStock": 1,
    "availableStock": 21,
    "minimumStock": 5,
    "maximumStock": 50,
    "reorderLevel": 8,
    "status": "In_Stock",
    "lastCountAt": "2026-09-23T00:00:00.000Z"
  },
  {
    "id": "INV-NRH-prod-7",
    "variantId": "var-prod-7-std",
    "warehouseId": "WH-002",
    "currentStock": 23,
    "reservedStock": 0,
    "availableStock": 23,
    "minimumStock": 3,
    "maximumStock": 30,
    "reorderLevel": 5,
    "status": "In_Stock",
    "lastCountAt": "2026-09-23T00:00:00.000Z"
  },
  {
    "id": "INV-MDC-prod-8",
    "variantId": "var-prod-8-std",
    "warehouseId": "WH-001",
    "currentStock": 29,
    "reservedStock": 1,
    "availableStock": 28,
    "minimumStock": 5,
    "maximumStock": 50,
    "reorderLevel": 8,
    "status": "In_Stock",
    "lastCountAt": "2026-09-23T00:00:00.000Z"
  },
  {
    "id": "INV-NRH-prod-8",
    "variantId": "var-prod-8-std",
    "warehouseId": "WH-002",
    "currentStock": 6,
    "reservedStock": 0,
    "availableStock": 6,
    "minimumStock": 3,
    "maximumStock": 30,
    "reorderLevel": 5,
    "status": "In_Stock",
    "lastCountAt": "2026-09-23T00:00:00.000Z"
  },
  {
    "id": "INV-MDC-prod-9",
    "variantId": "var-prod-9-std",
    "warehouseId": "WH-001",
    "currentStock": 36,
    "reservedStock": 1,
    "availableStock": 35,
    "minimumStock": 5,
    "maximumStock": 50,
    "reorderLevel": 8,
    "status": "In_Stock",
    "lastCountAt": "2026-09-23T00:00:00.000Z"
  },
  {
    "id": "INV-NRH-prod-9",
    "variantId": "var-prod-9-std",
    "warehouseId": "WH-002",
    "currentStock": 9,
    "reservedStock": 0,
    "availableStock": 9,
    "minimumStock": 3,
    "maximumStock": 30,
    "reorderLevel": 5,
    "status": "In_Stock",
    "lastCountAt": "2026-09-23T00:00:00.000Z"
  },
  {
    "id": "INV-MDC-prod-10",
    "variantId": "var-prod-10-std",
    "warehouseId": "WH-001",
    "currentStock": 13,
    "reservedStock": 1,
    "availableStock": 12,
    "minimumStock": 5,
    "maximumStock": 50,
    "reorderLevel": 8,
    "status": "In_Stock",
    "lastCountAt": "2026-09-23T00:00:00.000Z"
  },
  {
    "id": "INV-NRH-prod-10",
    "variantId": "var-prod-10-std",
    "warehouseId": "WH-002",
    "currentStock": 12,
    "reservedStock": 0,
    "availableStock": 12,
    "minimumStock": 3,
    "maximumStock": 30,
    "reorderLevel": 5,
    "status": "In_Stock",
    "lastCountAt": "2026-09-23T00:00:00.000Z"
  },
  {
    "id": "INV-MDC-prod-11",
    "variantId": "var-prod-11-std",
    "warehouseId": "WH-001",
    "currentStock": 20,
    "reservedStock": 1,
    "availableStock": 19,
    "minimumStock": 5,
    "maximumStock": 50,
    "reorderLevel": 8,
    "status": "In_Stock",
    "lastCountAt": "2026-09-23T00:00:00.000Z"
  },
  {
    "id": "INV-NRH-prod-11",
    "variantId": "var-prod-11-std",
    "warehouseId": "WH-002",
    "currentStock": 15,
    "reservedStock": 0,
    "availableStock": 15,
    "minimumStock": 3,
    "maximumStock": 30,
    "reorderLevel": 5,
    "status": "In_Stock",
    "lastCountAt": "2026-09-23T00:00:00.000Z"
  },
  {
    "id": "INV-MDC-prod-12",
    "variantId": "var-prod-12-std",
    "warehouseId": "WH-001",
    "currentStock": 27,
    "reservedStock": 1,
    "availableStock": 26,
    "minimumStock": 5,
    "maximumStock": 50,
    "reorderLevel": 8,
    "status": "In_Stock",
    "lastCountAt": "2026-09-23T00:00:00.000Z"
  },
  {
    "id": "INV-NRH-prod-12",
    "variantId": "var-prod-12-std",
    "warehouseId": "WH-002",
    "currentStock": 18,
    "reservedStock": 0,
    "availableStock": 18,
    "minimumStock": 3,
    "maximumStock": 30,
    "reorderLevel": 5,
    "status": "In_Stock",
    "lastCountAt": "2026-09-23T00:00:00.000Z"
  }
];
